on:
  workflow_call:
    inputs:
      NODE_VERSION:
        type: string
        description: node version
        required: true
      S3_BUCKET:
        type: string
        description: s3 bucket
        required: true
      BUILD_ENV:
        type: string
        description: build env for
        required: true
      NPM_BUILD_FOLDER:
        type: string
        description: npm build forder
        required: true
      AWS_CLOUDFRONT_ID:
        type: string
        description: cloudfront id
        required: true
      FEATURE_FLAGS:
        type: string
        description: generate active feature flags file
        required: false
      REF:
        type: string
        description: flag for custom ref
        required: false
    secrets:
      AWS_REGION:
        description: aws region
        required: true
      AWS_ACCESS_KEY_ID:
        description: aws access key
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: aws secret key
        required: true
      CHECKOUT_TOKEN:
        description: checkout token
        required: true
      NPM_TOKEN:
        description: npm token
        required: false
name: STAGE - Deploy
jobs:
  deploy:
    name: Deploy on env
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/checkout@v3
        with:
          repository: 'ananasGit/github-actions-workflow-templates-scripts'
          token: ${{ secrets.CHECKOUT_TOKEN }}
          path: 'workflow-scripts'

      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
        with:
          ref: master

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != '' &&
            inputs.REF == 'false'
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Add secrets in .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          $GITHUB_WORKSPACE/workflow-scripts/stage/add-secrets-in-npm.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Generate active feature flags file
        if: inputs.FEATURE_FLAGS  == 'true'
        run: |
          $GITHUB_WORKSPACE/workflow-scripts/dev/add-secrets-in-npm.sh

      - name: Install NPM dependencies
        env:
          BUILD_ENV: ${{ inputs.BUILD_ENV }}
        run: |
          npm install
          npm run build:${{ env.BUILD_ENV }}

      - name: Deploy static site to S3 bucket
        env:
          S3_BUCKET: ${{ inputs.S3_BUCKET }}
          NPM_BUILD_FOLDER: ${{ inputs.NPM_BUILD_FOLDER }}
          AWS_CLOUDFRONT_ID: ${{ inputs.AWS_CLOUDFRONT_ID }}
        run: |
          $GITHUB_WORKSPACE/workflow-scripts/stage/deploy-static-site-to-s3.sh